// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: game_proto/game.proto

package game_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player int32

const (
	Player_NONE  Player = 0
	Player_ZERO  Player = 1
	Player_CROSS Player = 2
)

// Enum value maps for Player.
var (
	Player_name = map[int32]string{
		0: "NONE",
		1: "ZERO",
		2: "CROSS",
	}
	Player_value = map[string]int32{
		"NONE":  0,
		"ZERO":  1,
		"CROSS": 2,
	}
)

func (x Player) Enum() *Player {
	p := new(Player)
	*p = x
	return p
}

func (x Player) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Player) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_game_proto_enumTypes[0].Descriptor()
}

func (Player) Type() protoreflect.EnumType {
	return &file_game_proto_game_proto_enumTypes[0]
}

func (x Player) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Player.Descriptor instead.
func (Player) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_game_proto_rawDescGZIP(), []int{0}
}

type ServerMessageType int32

const (
	ServerMessageType_UNDEFINED   ServerMessageType = 0 // error
	ServerMessageType_INIT_PLAYER ServerMessageType = 1 // send to player who is he
	ServerMessageType_MAKE_MOVE   ServerMessageType = 2 // say player to make move
	ServerMessageType_SAVE_MOVE   ServerMessageType = 3 // apply move
	ServerMessageType_END_GAME    ServerMessageType = 4 // finish game
)

// Enum value maps for ServerMessageType.
var (
	ServerMessageType_name = map[int32]string{
		0: "UNDEFINED",
		1: "INIT_PLAYER",
		2: "MAKE_MOVE",
		3: "SAVE_MOVE",
		4: "END_GAME",
	}
	ServerMessageType_value = map[string]int32{
		"UNDEFINED":   0,
		"INIT_PLAYER": 1,
		"MAKE_MOVE":   2,
		"SAVE_MOVE":   3,
		"END_GAME":    4,
	}
)

func (x ServerMessageType) Enum() *ServerMessageType {
	p := new(ServerMessageType)
	*p = x
	return p
}

func (x ServerMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_game_proto_enumTypes[1].Descriptor()
}

func (ServerMessageType) Type() protoreflect.EnumType {
	return &file_game_proto_game_proto_enumTypes[1]
}

func (x ServerMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerMessageType.Descriptor instead.
func (ServerMessageType) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_game_proto_rawDescGZIP(), []int{1}
}

type StartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_game_proto_rawDescGZIP(), []int{0}
}

type StartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Iam    Player `protobuf:"varint,2,opt,name=iam,proto3,enum=Player" json:"iam,omitempty"`
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *StartResponse) GetIam() Player {
	if x != nil {
		return x.Iam
	}
	return Player_NONE
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row     int32  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col     int32  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Who     Player `protobuf:"varint,3,opt,name=who,proto3,enum=Player" json:"who,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Finish  bool   `protobuf:"varint,5,opt,name=finish,proto3" json:"finish,omitempty"`
	Winner  Player `protobuf:"varint,6,opt,name=winner,proto3,enum=Player" json:"winner,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_game_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *Move) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Move) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *Move) GetWho() Player {
	if x != nil {
		return x.Who
	}
	return Player_NONE
}

func (x *Move) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Move) GetFinish() bool {
	if x != nil {
		return x.Finish
	}
	return false
}

func (x *Move) GetWinner() Player {
	if x != nil {
		return x.Winner
	}
	return Player_NONE
}

type MessageTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Time    string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *MessageTime) Reset() {
	*x = MessageTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTime) ProtoMessage() {}

func (x *MessageTime) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTime.ProtoReflect.Descriptor instead.
func (*MessageTime) Descriptor() ([]byte, []int) {
	return file_game_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *MessageTime) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageTime) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type GameClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row int32 `protobuf:"varint,10,opt,name=row,proto3" json:"row,omitempty"`
	Col int32 `protobuf:"varint,11,opt,name=col,proto3" json:"col,omitempty"`
}

func (x *GameClientMessage) Reset() {
	*x = GameClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameClientMessage) ProtoMessage() {}

func (x *GameClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameClientMessage.ProtoReflect.Descriptor instead.
func (*GameClientMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameClientMessage) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *GameClientMessage) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type GameServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	GameId  int32             `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Type    ServerMessageType `protobuf:"varint,3,opt,name=type,proto3,enum=ServerMessageType" json:"type,omitempty"`
	Who     Player            `protobuf:"varint,4,opt,name=who,proto3,enum=Player" json:"who,omitempty"`
	Row     int32             `protobuf:"varint,15,opt,name=row,proto3" json:"row,omitempty"`
	Col     int32             `protobuf:"varint,16,opt,name=col,proto3" json:"col,omitempty"`
}

func (x *GameServerMessage) Reset() {
	*x = GameServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServerMessage) ProtoMessage() {}

func (x *GameServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServerMessage.ProtoReflect.Descriptor instead.
func (*GameServerMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameServerMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameServerMessage) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameServerMessage) GetType() ServerMessageType {
	if x != nil {
		return x.Type
	}
	return ServerMessageType_UNDEFINED
}

func (x *GameServerMessage) GetWho() Player {
	if x != nil {
		return x.Who
	}
	return Player_NONE
}

func (x *GameServerMessage) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *GameServerMessage) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

var File_game_proto_game_proto protoreflect.FileDescriptor

var file_game_proto_game_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x03, 0x69, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x03, 0x69, 0x61, 0x6d, 0x22, 0x98, 0x01, 0x0a,
	0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6f, 0x6c, 0x12, 0x19, 0x0a, 0x03, 0x77, 0x68, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x03, 0x77, 0x68, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6f, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6f, 0x6c, 0x22, 0xac, 0x01,
	0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a,
	0x03, 0x77, 0x68, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x03, 0x77, 0x68, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6f,
	0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6f, 0x6c, 0x2a, 0x27, 0x0a, 0x06,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x5a, 0x45, 0x52, 0x4f, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x52,
	0x4f, 0x53, 0x53, 0x10, 0x02, 0x2a, 0x5f, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e,
	0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x49,
	0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x41,
	0x4b, 0x45, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x41, 0x56,
	0x45, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x4e, 0x44, 0x5f,
	0x47, 0x41, 0x4d, 0x45, 0x10, 0x04, 0x32, 0xb6, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x2c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x0d, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x1e, 0x0a,
	0x08, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x05, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x1a, 0x05, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x24, 0x0a,
	0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x1a, 0x0c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x12, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x21, 0x5a, 0x1f, 0x74, 0x69, 0x6b, 0x74, 0x61, 0x6b, 0x74, 0x6f, 0x65, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_game_proto_rawDescOnce sync.Once
	file_game_proto_game_proto_rawDescData = file_game_proto_game_proto_rawDesc
)

func file_game_proto_game_proto_rawDescGZIP() []byte {
	file_game_proto_game_proto_rawDescOnce.Do(func() {
		file_game_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_game_proto_rawDescData)
	})
	return file_game_proto_game_proto_rawDescData
}

var file_game_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_game_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_game_proto_game_proto_goTypes = []interface{}{
	(Player)(0),               // 0: Player
	(ServerMessageType)(0),    // 1: ServerMessageType
	(*StartRequest)(nil),      // 2: StartRequest
	(*StartResponse)(nil),     // 3: StartResponse
	(*Move)(nil),              // 4: Move
	(*MessageTime)(nil),       // 5: MessageTime
	(*GameClientMessage)(nil), // 6: GameClientMessage
	(*GameServerMessage)(nil), // 7: GameServerMessage
}
var file_game_proto_game_proto_depIdxs = []int32{
	0, // 0: StartResponse.iam:type_name -> Player
	0, // 1: Move.who:type_name -> Player
	0, // 2: Move.winner:type_name -> Player
	1, // 3: GameServerMessage.type:type_name -> ServerMessageType
	0, // 4: GameServerMessage.who:type_name -> Player
	2, // 5: Game.StartGame:input_type -> StartRequest
	4, // 6: Game.MakeMove:input_type -> Move
	5, // 7: Game.Test:input_type -> MessageTime
	6, // 8: Game.GameStream:input_type -> GameClientMessage
	3, // 9: Game.StartGame:output_type -> StartResponse
	4, // 10: Game.MakeMove:output_type -> Move
	5, // 11: Game.Test:output_type -> MessageTime
	7, // 12: Game.GameStream:output_type -> GameServerMessage
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_game_proto_game_proto_init() }
func file_game_proto_game_proto_init() {
	if File_game_proto_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_proto_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_game_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_game_proto_goTypes,
		DependencyIndexes: file_game_proto_game_proto_depIdxs,
		EnumInfos:         file_game_proto_game_proto_enumTypes,
		MessageInfos:      file_game_proto_game_proto_msgTypes,
	}.Build()
	File_game_proto_game_proto = out.File
	file_game_proto_game_proto_rawDesc = nil
	file_game_proto_game_proto_goTypes = nil
	file_game_proto_game_proto_depIdxs = nil
}
